name: kaspa_flutter_core
description: Pure-Dart Kaspa wallet SDK (logic + crypto + gRPC)
version: 0.1.0
homepage: https://github.com/kasanova/kaspa_flutter_core
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  convert: ^3.1.1
  crypto: ^3.0.3
  decimal: ^3.2.4
  fixnum: ^1.1.0
  hex: ^0.2.0
  pointycastle: ^4.0.0
  protobuf: ^4.1.0
  grpc: ^4.1.0
  logger: ^2.2.0
  fast_immutable_collections: ^11.0.4
  freezed_annotation: ^3.0.0
  intl: ^0.20.2
  http: ^1.4.0

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  freezed: ^3.0.6
